SELECT 
    MONTH(A.START_DATE) AS MONTH,
    A.CAR_ID,
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
INNER JOIN
(
    SELECT 
        CAR_ID,
        COUNT(CAR_ID) AS CNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        YEAR(START_DATE) = 2022
    AND
        MONTH(START_DATE) >= 8
    AND
        MONTH(START_DATE) <= 10
    GROUP BY CAR_ID
) B
ON 
    A.CAR_ID = B.CAR_ID
WHERE
    B.CNT >= 5
AND
    YEAR(A.START_DATE) = 2022
AND
    MONTH(A.START_DATE) >= 8
AND
    MONTH(A.START_DATE) <= 10
GROUP BY MONTH(A.START_DATE), A.CAR_ID
ORDER BY MONTH(A.START_DATE), A.CAR_ID DESC